# Generated by Django 3.0.3 on 2020-06-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('metrics', '0001_initial'),
        ('tags', '0002_auto_20200415_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('repo_url', models.CharField(max_length=1024, unique=True)),
            ],
            options={
                'verbose_name': 'development branch',
                'verbose_name_plural': 'development branches',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('color', models.CharField(max_length=6, unique=True)),
                ('urgency', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'priority label',
                'verbose_name_plural': 'priority labels',
                'ordering': ['urgency'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'status label',
                'verbose_name_plural': 'status labels',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('summary', models.TextField(max_length=512)),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('committed', models.BooleanField(default=False)),
                ('bounty_claimed', models.BooleanField(default=False)),
                ('bounty', models.FloatField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to=settings.AUTH_USER_MODEL)),
                ('bounty_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.Currency')),
                ('git_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qndbacklog.GitBranch')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qndbacklog.Priority')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='qndbacklog.Status')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Objective',
                'verbose_name_plural': 'project objectives',
                'ordering': ['priority', 'target_date'],
            },
        ),
    ]
