# Generated by Django 3.0.3 on 2020-06-08 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('qndbacklog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['-priority', '-target_date'], 'verbose_name': 'Project Objective', 'verbose_name_plural': 'project objectives'},
        ),
        migrations.AddField(
            model_name='objective',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
