# Generated by Django 3.0.7 on 2020-06-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qndbacklog', '0002_auto_20200608_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['-priority', 'target_date'], 'verbose_name': 'Project Objective', 'verbose_name_plural': 'project objectives'},
        ),
    ]
