# Generated by Django 3.0.7 on 2020-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qndbacklog', '0003_auto_20200612_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
