# Generated by Django 3.0.3 on 2020-04-23 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_weight_allocation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
