# Generated by Django 3.0.3 on 2020-03-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('images', '0004_auto_20200325_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/'),
        ),
    ]
