# Generated by Django 3.0.3 on 2020-03-27 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20200326_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
