# Generated by Django 3.0.3 on 2020-03-31 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_gallery_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.TextField(default='a curated collection of imagery', max_length=256),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Untitled', max_length=64),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(default='a picture is worth a thousand words.', max_length=256),
        ),
    ]
