# Generated by Django 3.0.3 on 2020-03-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20200331_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='credit',
            field=models.CharField(default='origin unknown', max_length=64),
        ),
    ]
