# Generated by Django 3.0.3 on 2020-04-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20200402_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(default='demo', max_length=40),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
