# Generated by Django 3.0.3 on 2020-04-02 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20200402_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='alt_text',
            new_name='title',
        ),
    ]
