# Generated by Django 3.0.3 on 2020-04-11 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20200406_2252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-creation_date']},
        ),
    ]
