# Generated by Django 3.0.3 on 2020-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marshmallows', '0001_initial'),
        ('images', '0013_auto_20200411_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AddField(
            model_name='image',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
    ]
