# Generated by Django 3.0.3 on 2020-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20200415_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
