# Generated by Django 3.0.3 on 2020-04-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20200417_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(max_length=255, upload_to='images/%Y/%m/%d/'),
        ),
    ]
