# Generated by Django 3.0.3 on 2020-04-23 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20200423_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(blank=True, max_length=255, upload_to='images/thumbnails/%Y/%m/%d/'),
        ),
    ]
