# Generated by Django 3.0.3 on 2020-04-29 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_auto_20200423_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(default=68, on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='images.Image'),
        ),
    ]
