# Generated by Django 3.0.3 on 2020-05-05 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marshmallows', '0001_initial'),
        ('tags', '0002_auto_20200415_1853'),
        ('images', '0018_gallery_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('number', models.PositiveIntegerField(default=1)),
                ('collection', models.CharField(default='unknown', max_length=32)),
                ('price', models.FloatField(default=0)),
                ('is_sold', models.BooleanField(default=False)),
                ('contact_name', models.CharField(max_length=64)),
                ('contact_link', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-number', '-creation_date'],
            },
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='marshmallows',
            field=models.ManyToManyField(to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='image',
            name='marshmallows',
            field=models.ManyToManyField(to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
