# Generated by Django 3.0.3 on 2020-05-05 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marshmallows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
        ('metrics', '0001_initial'),
        ('images', '0019_auto_20200505_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(to='people.Artist'),
        ),
        migrations.AddField(
            model_name='piece',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.Currency'),
        ),
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='images.Image'),
        ),
        migrations.AddField(
            model_name='piece',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AddField(
            model_name='piece',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='pieces',
            field=models.ManyToManyField(to='images.Piece'),
        ),
    ]
