# Generated by Django 3.0.3 on 2020-05-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('images', '0022_auto_20200505_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metrics.Currency'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
