# Generated by Django 3.0.3 on 2020-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_auto_20200505_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='medium',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
