# Generated by Django 3.0.3 on 2020-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_piece_medium'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
