# Generated by Django 3.0.3 on 2020-05-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200415_1853'),
        ('images', '0025_piece_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
