# Generated by Django 3.0.3 on 2020-05-11 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200415_1853'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marshmallows', '0001_initial'),
        ('images', '0026_piece_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='image',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='image',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
