# Generated by Django 3.0.3 on 2020-05-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20200511_1941'),
        ('images', '0027_auto_20200511_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='artists',
            field=models.ManyToManyField(blank=True, to='people.Artist'),
        ),
    ]
