# Generated by Django 3.0.3 on 2020-05-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0028_auto_20200511_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(max_length=40, null=True, unique=True),
        ),
    ]
