# Generated by Django 3.0.3 on 2020-05-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0029_piece_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
