# Generated by Django 3.0.3 on 2020-05-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0032_auto_20200523_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['number', '-creation_date']},
        ),
    ]
