# Generated by Django 3.0.3 on 2020-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('images', '0033_auto_20200523_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='depth_unit',
            field=models.ManyToManyField(blank=True, related_name='piece_depth_unit', to='metrics.Distance'),
        ),
        migrations.AddField(
            model_name='piece',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='length_unit',
            field=models.ManyToManyField(blank=True, related_name='piece_length_unit', to='metrics.Distance'),
        ),
        migrations.AddField(
            model_name='piece',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='mass_unit',
            field=models.ManyToManyField(blank=True, related_name='piece_mass_unit', to='metrics.Mass'),
        ),
        migrations.AddField(
            model_name='piece',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='width_unit',
            field=models.ManyToManyField(blank=True, related_name='piece_width_unit', to='metrics.Distance'),
        ),
        migrations.AddField(
            model_name='piece',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
