# Generated by Django 3.0.7 on 2020-06-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0035_auto_20200608_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption',
            field=models.TextField(default='a curated collection of imagery', help_text='Provide a short description the artists and art. Tell the story behind the work.', max_length=256),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='cover_image',
            field=models.ForeignKey(help_text='Provide an advertisement to attract attention to the gallery. This image will appear as the first image in the gallery and in listings.', on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='pieces',
            field=models.ManyToManyField(help_text='Select the pieces that you want to include in the gallery.', to='images.Piece'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(help_text='The slug will be used in the URL for your update. Slugs may only use letters, numbers, hyphens, and underscores. Spaces are not allowed. To help your update appear in relevant search engine queries, please use a slug that is similar to your title.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(default='Untitled', help_text='The title will be shown in listings and on the top of the page.', max_length=64),
        ),
    ]
