# Generated by Django 3.0.3 on 2020-05-05 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_auto_20200505_0149'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marshmallows', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['weight', '-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['weight', '-creation_date']},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['weight', '-creation_date']},
        ),
        migrations.AddField(
            model_name='person',
            name='marshmallows',
            field=models.ManyToManyField(to='marshmallows.Marshmallow'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quote',
            name='marshmallows',
            field=models.ManyToManyField(to='marshmallows.Marshmallow'),
        ),
        migrations.AddField(
            model_name='quote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Image'),
        ),
    ]
