# Generated by Django 3.0.3 on 2020-05-11 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20200415_1853'),
        ('marshmallows', '0001_initial'),
        ('people', '0003_auto_20200507_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quote',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
