# Generated by Django 3.0.3 on 2020-05-11 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20200511_1614'),
        ('accounts', '0002_auto_20200423_0538'),
        ('people', '0004_auto_20200511_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='media',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='statement',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_town',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='links',
            field=models.ManyToManyField(blank=True, to='links.Link'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
    ]
