# Generated by Django 3.0.7 on 2020-06-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200608_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
