# Generated by Django 3.0.3 on 2020-03-04 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('caption', models.CharField(default='a picture is worth a thousand words.', max_length=256)),
                ('alt_text', models.CharField(default='a compelling image', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='HeadlineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('caption', models.CharField(default='a picture is worth a thousand words.', max_length=256)),
                ('alt_text', models.CharField(default='a compelling image', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='an external link', max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=256)),
                ('author', models.CharField(default='an unknown subject', max_length=256)),
                ('slug', models.SlugField(max_length=40)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(default='an undisclosed location', max_length=256)),
                ('headline', models.CharField(default='EXTRA!', max_length=256)),
                ('introduction', models.CharField(default='Introducing..', max_length=500)),
                ('content', models.CharField(default='A new kind of content...', max_length=5000)),
                ('conclusion', models.CharField(default='Coming to your world view.', max_length=5000)),
                ('external_links', models.ManyToManyField(to='updates.Link')),
                ('featured_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.FeaturedImage')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.Gallery')),
                ('headline_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updates.HeadlineImage')),
                ('tags', models.ManyToManyField(to='updates.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(to='updates.Tag'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('caption', models.CharField(default='a picture is worth a thousand words.', max_length=256)),
                ('alt_text', models.CharField(default='a compelling image', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='pictures',
            field=models.ManyToManyField(to='updates.Image'),
        ),
    ]
