# Generated by Django 3.0.3 on 2020-03-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('images', '0001_initial'),
        ('links', '0001_initial'),
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='pictures',
        ),
        migrations.RemoveField(
            model_name='headlineimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.RemoveField(
            model_name='link',
            name='tags',
        ),
        migrations.AlterField(
            model_name='update',
            name='conclusion',
            field=models.CharField(blank=True, default='Coming to your world view.', max_length=5000),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.CharField(blank=True, default='A new kind of content...', max_length=5000),
        ),
        migrations.AlterField(
            model_name='update',
            name='external_links',
            field=models.ManyToManyField(blank=True, to='links.Link'),
        ),
        migrations.AlterField(
            model_name='update',
            name='featured_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_featured', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gallery',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='images.Gallery'),
        ),
        migrations.AlterField(
            model_name='update',
            name='headline_img',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_headline', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.CharField(blank=True, default='Introducing..', max_length=500),
        ),
        migrations.AlterField(
            model_name='update',
            name='location',
            field=models.CharField(blank=True, default='an undisclosed location', max_length=256),
        ),
        migrations.AlterField(
            model_name='update',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.DeleteModel(
            name='FeaturedImage',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='HeadlineImage',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
