# Generated by Django 3.0.3 on 2020-03-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('links', '0001_initial'),
        ('tags', '0001_initial'),
        ('updates', '0002_auto_20200310_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='conclusion',
            field=models.CharField(blank=True, default='Coming to your world view.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.CharField(blank=True, default='A new kind of content...', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='external_links',
            field=models.ManyToManyField(blank=True, null=True, to='links.Link'),
        ),
        migrations.AlterField(
            model_name='update',
            name='featured_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_featured', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='images.Gallery'),
        ),
        migrations.AlterField(
            model_name='update',
            name='headline_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_headline', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.CharField(blank=True, default='Introducing..', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='tags.Tag'),
        ),
    ]
