# Generated by Django 3.0.3 on 2020-03-10 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('tags', '0001_initial'),
        ('updates', '0003_auto_20200310_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='conclusion',
            field=models.TextField(blank=True, default='Coming to your world view.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, default='A new kind of content...', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='external_links',
            field=models.ManyToManyField(blank=True, to='links.Link'),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.TextField(blank=True, default='Introducing..', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
    ]
