# Generated by Django 3.0.3 on 2020-03-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0004_auto_20200310_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='update',
            old_name='external_links',
            new_name='links',
        ),
        migrations.RemoveField(
            model_name='update',
            name='author',
        ),
    ]
