# Generated by Django 3.0.3 on 2020-04-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_auto_20200402_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
