# Generated by Django 3.0.3 on 2020-05-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0009_auto_20200415_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='marshmallows',
        ),
        migrations.RemoveField(
            model_name='update',
            name='weight',
        ),
    ]
