# Generated by Django 3.0.3 on 2020-05-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marshmallows', '0001_initial'),
        ('updates', '0010_auto_20200511_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='marshmallows.Marshmallow'),
        ),
        migrations.AddField(
            model_name='update',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
