# Generated by Django 3.0.3 on 2020-06-03 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20200513_2207'),
        ('images', '0034_auto_20200603_1727'),
        ('updates', '0012_auto_20200511_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='artists',
            field=models.ManyToManyField(blank=True, to='people.Artist'),
        ),
        migrations.AddField(
            model_name='update',
            name='artwork',
            field=models.ManyToManyField(blank=True, to='images.Piece'),
        ),
        migrations.AlterField(
            model_name='update',
            name='conclusion',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='location',
            field=models.CharField(default='an undisclosed location', max_length=256),
        ),
    ]
