# Generated by Django 3.0.7 on 2020-06-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20200608_1556'),
        ('links', '0006_link_last_modified'),
        ('images', '0035_auto_20200608_1556'),
        ('updates', '0014_update_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='artists',
            field=models.ManyToManyField(blank=True, help_text='Are you introducing a new artist or mentioning an old one? Include links to their profiles in the update.', to='people.Artist'),
        ),
        migrations.AlterField(
            model_name='update',
            name='artwork',
            field=models.ManyToManyField(blank=True, help_text='Do you want to show off some artwork that you or another member has published? Choose which pieces you would like to showcase in the update.', to='images.Piece'),
        ),
        migrations.AlterField(
            model_name='update',
            name='conclusion',
            field=models.TextField(blank=True, help_text="Reiterate important context, details, and restate your arguments and observations. Drive your point home and don't forget to include shout-outs or sources.", max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, help_text='Include factual infomation such as who, what, when, where, why and how. This is where the details of the update are made clear.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='featured_img',
            field=models.ForeignKey(blank=True, help_text='Choose a single image that illustrates the narative of your update. Your featured image will be displayed prominently amidst the content on the page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_featured', to='images.Image', verbose_name='featured image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Do you want to let people know about a new gallery you or another member has published? Choose a gallery to showcase in the update.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery'),
        ),
        migrations.AlterField(
            model_name='update',
            name='headline',
            field=models.CharField(default='EXTRA!', help_text='Grab attention with a short gist of what your update is about. The headline will appear at the top of the page and on the home page if it has been published recently.', max_length=256),
        ),
        migrations.AlterField(
            model_name='update',
            name='headline_img',
            field=models.ForeignKey(blank=True, help_text='Choose a single image to set the mood of the update. Your headline will be super-imposed over the image you choose. It is recommended to use an image at least 800 pixles wide and 500 pixels high. Avoid using small or low resolution images or images that have a portrait orientation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_headline', to='images.Image', verbose_name='headline image'),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.TextField(blank=True, help_text='Simply state the context and content of the update. Your audience are people that only read the first few lines on a page', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='links',
            field=models.ManyToManyField(blank=True, help_text='Did you mention anything in the update that might have online resources outside of this site? If so, you may add existing links. They will appear at the bottom of the page.', to='links.Link'),
        ),
        migrations.AlterField(
            model_name='update',
            name='location',
            field=models.CharField(default='an undisclosed location', help_text="Let your readers know where you are reporting from. Feel free to skip this field or to make something up if you don't feel safe or comfortable disclosing your location.", max_length=256),
        ),
        migrations.AlterField(
            model_name='update',
            name='slug',
            field=models.SlugField(help_text='The slug will be used in the URL for your update. Slugs may only use letters, numbers, hyphens, and underscores. Spaces are not allowed. To help your update appear in relevant search engine queries, please use a slug that is similar to your title.', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(default='Untitled', help_text='The title will be shown in listings and below the headline on the page.', max_length=256),
        ),
    ]
