# Generated by Django 3.0.7 on 2020-06-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0036_auto_20200615_2110'),
        ('updates', '0015_auto_20200612_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='artwork',
            field=models.ManyToManyField(blank=True, help_text='Do you want to show off some artwork that you have contributed? Choose which pieces you would like to showcase in the update.', to='images.Piece'),
        ),
        migrations.AlterField(
            model_name='update',
            name='gallery',
            field=models.ForeignKey(blank=True, help_text='Do you want to let people know about a new gallery you have curated? Choose a gallery to showcase in the update.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.Gallery'),
        ),
        migrations.AlterField(
            model_name='update',
            name='headline',
            field=models.CharField(help_text='Grab attention with a short gist of what your update is about. The headline will appear at the top of the page and on the home page if it has been published recently.', max_length=256),
        ),
        migrations.AlterField(
            model_name='update',
            name='introduction',
            field=models.TextField(blank=True, help_text='State the context and content of the update. Your audience are people that only read the first few lines on a page.', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='location',
            field=models.CharField(blank=True, help_text="Let your readers know where you are reporting from. Feel free to skip this or to make something up if you don't feel safe or comfortable disclosing your location.", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(help_text='The title will be shown in listings and below the headline on the page.', max_length=256),
        ),
    ]
