# Generated by Django 3.0.3 on 2020-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='an external link', max_length=64)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField()),
                ('images', models.ManyToManyField(blank=True, to='images.Image')),
            ],
        ),
    ]
