# Generated by Django 3.0.3 on 2020-04-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20200327_1809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, default='information you may find useful', max_length=256),
        ),
    ]
