# Generated by Django 3.0.3 on 2020-05-11 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20200415_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='publication_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
