# Generated by Django 3.0.3 on 2020-06-08 15:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_auto_20200511_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
